import { UserRole } from "@/generated/prisma";
import { createAccessControl } from "better-auth/plugins/access";
import {
  adminAc,
  defaultStatements,
  userAc,
} from "better-auth/plugins/admin/access";

const CRUD = ["create", "read", "update", "delete"] as const;

const statement = {
  ...defaultStatements,
  traits: CRUD,
  sideEffects: CRUD,
  laws: CRUD,
  nationalities: CRUD,
  vehicle_types: CRUD,
  resource_types: CRUD,
  resources: CRUD,
  captain_roles: CRUD,
  crew_levels: CRUD,
  auto_route_types: CRUD,
  building_types: CRUD,
  building_backroom: CRUD,
  building_size: CRUD,
  building_passive_production: CRUD,
  building_passive_production_duration: CRUD,
  playthrough: CRUD,
  crew_member: CRUD,
  crew_experience: CRUD,
  police_officers: CRUD,
  auto_route: CRUD,
} as const;

export const ac = createAccessControl(statement);

export const roles = {
  [UserRole.USER]: ac.newRole({
    ...userAc.statements,
    user: [...userAc.statements.user],
    sideEffects: ["read"],
    traits: ["read"],
    laws: ["read"],
    nationalities: ["read"],
    vehicle_types: ["read"],
    resource_types: ["read"],
    resources: ["read"],
    captain_roles: ["read"],
    crew_levels: ["read"],
    auto_route_types: ["read"],
    building_types: ["read"],
    building_backroom: ["read"],
    building_size: ["read"],
    building_passive_production: ["read"],
    building_passive_production_duration: ["read"],
    playthrough: [...statement.playthrough],
    crew_member: [...statement.crew_member],
    crew_experience: [...statement.crew_experience],
    police_officers: [...statement.police_officers],
    auto_route: [...statement.auto_route],
  }),
  [UserRole.ADMIN]: ac.newRole({
    ...adminAc.statements,
    user: ["list", "ban"],
    sideEffects: [...statement.sideEffects],
    traits: [...statement.traits],
    laws: [...statement.laws],
    nationalities: [...statement.nationalities],
    vehicle_types: [...statement.vehicle_types],
    resource_types: [...statement.resource_types],
    resources: [...statement.resources],
    captain_roles: [...statement.captain_roles],
    crew_levels: [...statement.crew_levels],
    auto_route_types: [...statement.auto_route_types],
    building_types: [...statement.building_types],
    building_backroom: [...statement.building_backroom],
    building_size: [...statement.building_size],
    building_passive_production: [...statement.building_passive_production],
    building_passive_production_duration: [
      ...statement.building_passive_production_duration,
    ],
    playthrough: [...statement.playthrough],
    crew_member: [...statement.crew_member],
    crew_experience: [...statement.crew_experience],
    police_officers: [...statement.police_officers],
    auto_route: [...statement.auto_route],
  }),
  [UserRole.OWNER]: ac.newRole({
    ...adminAc.statements,
    user: [...adminAc.statements.user],
    sideEffects: [...statement.sideEffects],
    traits: [...statement.traits],
    laws: [...statement.laws],
    nationalities: [...statement.nationalities],
    vehicle_types: [...statement.vehicle_types],
    resource_types: [...statement.resource_types],
    resources: [...statement.resources],
    captain_roles: [...statement.captain_roles],
    crew_levels: [...statement.crew_levels],
    auto_route_types: [...statement.auto_route_types],
    building_types: [...statement.building_types],
    building_backroom: [...statement.building_backroom],
    building_size: [...statement.building_size],
    building_passive_production: [...statement.building_passive_production],
    building_passive_production_duration: [
      ...statement.building_passive_production_duration,
    ],
    playthrough: [...statement.playthrough],
    crew_member: [...statement.crew_member],
    crew_experience: [...statement.crew_experience],
    police_officers: [...statement.police_officers],
    auto_route: [...statement.auto_route],
  }),
};
